version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    reviewers:
      - ulises-jeremias
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /scripts/ci
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    reviewers:
      - ulises-jeremias
    groups:
      pip:
        patterns:
          - "*"
